import { Assets } from "assets.slint";
import { Theme } from "theme.slint";
import { Card, ParameterCard, CircularGauge, PowerGauge } from "widgets.slint";


export component AppWindow inherits Window {
    title: "Smart Home Dashboard - Koaley Group";
    width: 1020px;
    height: 720px;
    background: Theme.palette.blue-pink-gradient;
    icon: Assets.logo;

    // 
    in property <[{label: string, icon: image}]> home-locations: [];
    HorizontalLayout {
        padding: 70px;
        spacing: Theme.dimensions.spacing;
        VerticalLayout {
            width: 390px;
            spacing: 16px;
            Card {
                vertical-stretch: 0.4;
            }

            Card { }

            Card {
                vertical-stretch: 0.25;
            }
        }

        VerticalLayout {
            width: 160px;
            spacing: 8px;
            ParameterCard {
                label: "Temperature";
                value: 25.4;
                units: "ºC";
            }

            ParameterCard {
                label: "Humidity";
                value: 56;
                units: "%";
            }

            ParameterCard {
                label: "Heating";
                value: 35;
                units: "ºC";
            }

            ParameterCard {
                label: "Water";
                value: 234;
                units: "kpa";
            }
        }

        VerticalLayout {
            spacing: 16px;

            Card {
                height: self.width;

                // Display power circular progress bar
                PowerGauge {
                    width: parent.width;
                    height: parent.height;
                }
            }

            Card { }

            Card { }
        }
    }
}
